### ISSUE TITLE
Inventory prototype

### ISSUE THREAD

**Issue by rh5140** [rh5140/srs-team-bug#7]
Persistent state between scenes
For now, this will just be the inventory!
Refer to [this article](https://blog.unity.com/technology/persistent-data-how-to-save-your-game-states-and-settings) for how to use save states. We will be using [JsonUtility](https://docs.unity3d.com/2020.2/Documentation/Manual/JSONSerialization.html) for now. Note that since MonoBehaviors cannot be serialized, there will need to be a separate state class and manager class. 
Also refer to [this article](https://docs.unity3d.com/ScriptReference/Application-persistentDataPath.html) for where to store persistent data.

**Comment by kevinhong29** [comment]
-Added a scriptable object to hold BugData for a collectibles menu 
-Added a scriptable object InventorySystem to create Collection inventory to hold all discovered bugs
-Added temporary PlayerObject to have collection 
-Added temporary BugData ant and spider
-Added collection scene for collection menu, main menu button for collection, and a back button to go back to main menu
-Added some temporary prefabs for images 
-Added DisplayInventory script that updates the collection scene
-Updated UI script for new buttons
-Added scriptable object BugDatabaseObject for a database of bugs in order to deserialize save files 
-Added save and load methods in InventorySystem to save into and load from persistent data path
-Added temporary hotkeys to PlayerObject to save, load, add ant, add spider to test persistent state and added clear collection after quit
